- getting_started.ipynb
Remove dependency on external `wget` and `ls` in the getting_started.ipynb notebook.
> Use pure python to download demodata_geolife.gpkg

- movingpandas/trajectory.py
Geopandas 0.7 will come with pyproj.CRS class under gdf.crs, so following will not work in the next release as it expects `self.crs` to be a dict. See https://github.com/geopandas/geopandas/pull/1101 for details. 
https://github.com/anitagraser/movingpandas/blob/01417e5b2ab8e3b06f8060cbcee934673ea7b4e4/movingpandas/trajectory.py#L115-L126
This fix ensures compatibility with future releases of geopandas as well as older ones. `crs.is_geographic` checks for any lon/lat projection, not only WGS84. I assume that it is expected behaviour anyway.
cc https://github.com/pyOpenSci/software-review/issues/18
> Trajectory.is_latlon() update for GeoPandas 0.7

- movingpandas/tests/test_trajectory.py
- movingpandas/trajectory.py
- movingpandas/trajectory_aggregator.py
Use geometry column name when accessing the geometry in a series. 
Even after 13304fcc55f5af2ae6439a512e02dea27d901c23 was merged I was still seeing issues. The issue appears to be that the existing code assumes that all series will have a geometry column but this is not the case if a custom geometry column is used.
All tests pass with this change.
> Additional fixes for #62

- movingpandas/tests/test_trajectory_aggregator.py
- movingpandas/trajectory_aggregator.py
This sets the coordinate reference system to be the same as the source coordinate reference system of the trajectories.
> Preserve the coordinate reference system when returning geodataframes

- movingpandas/point_clusterer.py
- movingpandas/tests/test_point_clusterer.py
If the points are aligned either vertically or horizontally the point
clusterer was crashing as the number of rows or cols would be zero.
> Fix a crash when points are aligned

- movingpandas/geometry_utils.py
Constructing LineStrings is more expensive than constructing a
MultiPoint, and from the minimum rotated rectangle perspective it should
make no difference if it is a set of lines or a set of points.
> Speed up mrr_diagonal() by using MultiPoint instead of LineString

- environment.yml
closes #150
Opted to specify 3.9 (as opposed to python) In case 3.10 comes along and breaks things.
Sorted libraries.
Removed `bokeh` and is it a dependency of `hvplot` (`mamba repoquery depends hvplot -c conda-forge`).
Add `pre-commit`.
> WIP: update environment.yml

- .github/workflows/tests.yaml
Related to https://github.com/anitagraser/movingpandas/issues/143
In theory after this merges when some makes a PR it'll kick off pre-commit checks
This taken directly from https://github.com/geopandas/geopandas/blob/master/.github/workflows/tests.yaml#L1-L22
> Create Github action for pre-commit

- movingpandas/geometry_utils.py
- movingpandas/tests/test_geometry_utils.py
- movingpandas/trajectory_stop_detector.py
Approximately half of the time of mrr_diagonal() is spent creating shapely MultiPoint
instances with the entire list of points.
In order to speed this up, iteratively add points to one single MultiPoint instance by
using the union() operator.
Also, instead of iterating over the dataframe rows and then select the desired column,
select the series just once and iterate over its values.
> Optimize stop point detection by avoid re-creating shapely objects

- movingpandas/__init__.py
I realize I was in favor of this in https://github.com/anitagraser/movingpandas/issues/178
However, if you are not using `trajectory_smoother.py` I feel the message adds noise.
Moreso, i'm trying to capture the version in a shell environment as it's not currently possbile
```
export VERSION=$(python -c "import movingpandas; print(movingpandas.__version__)")
echo $VERSION
INFO: Missing optional dependencies. To use the trajectory smoother classes please install Stone Soup (see https://stonesoup.readthedocs.io/en/latest/#installation). 0.10.rc1
```
> skip missing optional deps message on import

- movingpandas/geometry_utils.py
- movingpandas/tests/test_geometry_utils.py
Fixed typo in mrr_diagonal as described in issue #249 . Pytest tests ran and all passed.
> Issue 249: Fixed typo in mrr_diagonal

- .github/workflows/release_to_pypi.yml
taken from geopandas https://github.com/geopandas/geopandas/blob/main/.github/workflows/release_to_pypi.yml
should simplify the release procedure.
This should trigger when a tag is created which start with v.
You'll have to add your PYPI_API_TOKEN in the settings of this repo.
I'm also motivated with this to upload the wheels as well to pypi https://github.com/anitagraser/movingpandas/discussions/238#discussioncomment-3616953
> Create release_to_pypi.yml github action

- .pre-commit-config.yaml
This PR resolves #256
xref geopandas/geopandas#2651, shapely/shapely#1614
> update pre-commit for flake8 moving to GH

- movingpandas/trajectory_aggregator.py
Expected parameter is actually timedelta and not int, adjusting the docstring to reflect that. 
Regarding the parameter type, timedelta is preferrable to int as discussed here: https://github.com/anitagraser/movingpandas/pull/279
> Modify TrajectoryCollectionAggregator docstring to timedelta instead of int

- movingpandas/io.py
- movingpandas/tests/test_io.py
This pull request adds the gdf_to_mf_json method to the codebase. The gdf_to_mf_json method converts a GeoDataFrame to a dictionary compatible with the Moving Features JSON (MF-JSON) specification.
More precisely, the method transforms a **GeoDataFrame** made of Point geometries into a **Feature Collection** object. It can handle multiple trips with _different_ timestamps. The name of the columns that should be considered temporal properties can also be provided in order to include them as such in the resulting dictionary.
```
gdf = GeoDataFrame(...)
mf_json = gdf_to_mf_json(
gdf=gdf,
traj_id_property="trajectory_id",
datetime_column="timestamp",
temporal_properties=["speed", "acceleration"],
temporal_properties_static_fields={
"speed": {"uom": "m/s"},
"acceleration": {"uom": "m/s^2"}
}, …
```
> GeoDataFrame to MF-JSON

- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory_collection.py
This pull request adds the timestamp column to the dataframe returned by the **_get_locations_at_** method of the **_TrajectoryCollection_** class. This has for consequence that the get_start_locations and get_end_locations now also return the timestamp column.
Solving: #318
> Adding the timestamp column to the df returned by get_locations_at for a TrajectoryCollection

- movingpandas/io.py
- movingpandas/point_clusterer.py
- movingpandas/tests/test_io.py
- movingpandas/tools/_show_versions.py
- movingpandas/trajectory.py
The only way of parsing an MF-JSON file is through the read_mf_file function. This forces the user working with in-memory data to write the data to a temporary file.
The proposed function allows one to parse the data from a dictionary directly. 
The read_mf_file is now a wrapper around it, so there is no duplication of logic.
(It would be really nice if it could make it to the package before 13th of November 😃 (Sigspatial))
> Adding read_mf_dict function

- movingpandas/trajectory_collection.py
Fixing regression in 89f2acf causing `add_timedelta` to add distance instead.
I have *not* run the test suite locally, and I also haven't added any new tests to prevent this bug in future.
> Fix typo in TrajectoryCollection.add_timedelta() adding distance instead

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
Linting started failing: 
```
Run pre-commit/action@v2.0.3
install pre-commit
/opt/hostedtoolcache/Python/3.12.[7](https://github.com/movingpandas/movingpandas/actions/runs/11265688955/job/31327930931#step:4:8)/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pycqa/flake8')
==> At key: hooks
==> At Hook(id='flake8')
==> At key: language
=====> Expected one of conda, coursier, dart, docker, docker_image, dotnet, fail, golang, haskell, lua, node, perl, pygrep, python, r, ruby, rust, script, swift, system but got: 'python_venv'
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: The process …
```
> Update failing linting stage

- .github/workflows/tests.yaml
Should fix the testing errors due to deprecated mambaforge https://github.com/movingpandas/movingpandas/actions/runs/12540405549/job/34967653677#step:3:122
```
Extracting mamba-1.5.11-py312h9460a1c_0.conda
Warning: Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at [https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/.](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/)
Warning: ERROR: executing pre_install.sh failed
ERROR: executing pre_install.sh failed
Error: The process '/usr/bin/bash' failed with exit code 1
```
Based on https://github.com/geopandas/geopandas/blob/37cf1ab2b452ff059e4dd57a298a6fa07b1311ed/.github/workflows/tests.yaml
> Switch to micromamba

- movingpandas/overlay.py
- movingpandas/tests/test_overlay.py
- movingpandas/tests/test_trajectory_collection.py
Addresses #263 
Uses `pytest`'s `tmp_path` to write GPKG files inside a temporary directory. The files are then deleted automatically after the tests complete: https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html
> Use temp directory for GPKG in tests

- movingpandas/trajectory_splitter.py
Minor issue:
- Accidentally a print statement was added, now removed.
I could add a flake8 or similar check in the github workflow to prevent this if I continue the cpa in the next weeks.
> Remove debugging print statement

- movingpandas/tests/test_trajectory_stop_detector.py
- movingpandas/trajectory_stop_detector.py
Closes #459
This PR implements the discussed changes to support `n_processes` while maintaining backward compatibility.
A `DeprecationWarning` is issued whenever `n_threads` is explicitly used. Additionally, a `ValueError` is raised if both `n_threads` and `n_processes` are provided together.
Two basic tests are included to:
- Check that the deprecation warning is issued correctly
- Ensure the `ValueError` is raised when both arguments are used
> Use `n_processes` instead of `n_threads` in `TrajectoryStopDetector`

- movingpandas/tests/test_trajectory_splitter.py
- movingpandas/trajectory_splitter.py
Closes #461 
- There are some minor internal API changes to facilitate this but nothing on the user-facing end.
- The tests are taken from the single-processing version and expanded to use multiprocessing. I hope that is okay.
- Also, renamed a test method inside `test_trajectory_splitter.py` to follow proper naming convention.
Let me know what you think about it, @anitagraser
> Add multiprocess support to `TrajectorySplitters`

- movingpandas/tests/test_trajectory.py
- movingpandas/trajectory.py
otherwise trying to work with a copy can result in:
```
traj.copy().populate_geometry_column()
...
File [/srv/conda/envs/notebook/lib/python3.12/site-packages/movingpandas/trajectory.py:196](https://gfts.minrk.net/srv/conda/envs/notebook/lib/python3.12/site-packages/movingpandas/trajectory.py#line=195), in Trajectory.requires_geometry.<locals>.wrapper(self, *args, **kwargs)
193 @wraps(func)
194 def wrapper(self, *args, **kwargs):
195     if self.df.geometry.isnull().all():
--> 196         self.populate_geometry_column()
197     return func(self, *args, **kwargs)
File [/srv/conda/envs/notebook/lib/python3.12/site-packages/movingpandas/trajectory.py:203](https://gfts.minrk.net/srv/conda/envs/notebook/lib/python3.12/site-packages/movingpandas/trajectory.py#line=202), in …
```
> include x, y in copy
