- trajectory_predictor.py
Pushed the revised version of the kinetic prediction.
> Revised kinetic prediction method

- .gitignore
- tests/test_trajectory_predictor.py
Updated tests for new version of the kinetic prediction.
> Updated unit tests for kinetic prediction.

- environment.yml
- requirements.txt
@anitagraser this should "just work" with binder.
> Use a conda environment

- tests/test_trajectory.py
- trajectory.py
It's my first attempt to commit to an open source project, so please be kind!
`traj.plot()` works:
Passing additional arguments too:
I've added `Trajectory._connect_points()` as a duplicate of `overlay._connect_points`! Maybe some refactoring is needed?
Plus: What should `plot()` be able to do? I've implemented it in a way, so that it passes `*args` and `*kwargs` to the `plot()` method of a `GeoDataFrame`. This way you could do thinks like `traj.plot(column="speed")`. Any additional requirements? 
I guess, I should also add some tests, right?
I've also deleted some unused imports.
> implement basic plot() method

- setup.py
The only difference I could spot between the last working and current failing build...
> Pin shapely to 1.7a3

- movingpandas/trajectory_plotter.py
> Fix axis handling in _TrajectoryCollectionPlotter

- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory_collection.py
- movingpandas/trajectory_plotter.py
Fixes #90 and adds TrajectoryCollection.copy() method
> Ensure _TrajectoryPlotter does not modify the provided trajectories

- .gitignore
- movingpandas/tests/test_trajectory_stop_detector.py
- movingpandas/trajectory_splitter.py
> Fix StopSplitter Error

- movingpandas/geometry_utils.py
- movingpandas/tests/test_geometry_utils.py
- movingpandas/trajectory.py
- movingpandas/trajectory_aggregator.py
- movingpandas/trajectory_generalizer.py
- setup.py
This pull request resolves #4 
Added a function _measure_distance_geodesic_ to geometry_utils. 
This method replaces _geometry_utils.measure_distance_euclidean_
Tested on windows in a fresh conda environment.
Hope this helps.
> resolves #4 - Use Geopy to compute distances

- movingpandas/tests/test_trajectory_splitter.py
- movingpandas/trajectory_splitter.py
for discarding trajectories with anomalous speeds
> added max_speed optional argument on SpeedSplitter

- movingpandas/tests/test_trajectory_stop_detector.py
- movingpandas/trajectory_stop_detector.py
> Fix TrajectoryStopDetector.get_stop_points to check if len(stops) > 0

- movingpandas/tests/test_trajectory.py
- movingpandas/trajectory.py
> added function to return MCP and related test

- movingpandas/tests/test_trajectory.py
- movingpandas/trajectory.py
- movingpandas/trajectory_plotter.py
Closes https://github.com/anitagraser/movingpandas/issues/134
> add speed name arg

- docs/requirements.txt
- readthedocs.yml
Fix #145, follow-up to #154, should be OK now (sorry for the noise).
> Fix error in RTD configuration

- movingpandas/tests/test_trajectory_splitter.py
- movingpandas/trajectory_splitter.py
> add split mode=hour

- movingpandas/trajectory_aggregator.py
The following changes were made:
- Avoid computing the unary union of cells for all points (since the cells themselves
don't change)
- Instead of iterating over DataFrame rows and then selecting the column, iterate over the
Series directly (since it also has the two needed pieces: index and geometry)
- Instead of DataFrame.iloc[<some_index>]["geometry"], save a pointer to the geometry series
and then do Series.iloc[<some_index>] directly.
> Small optimizations for the trajectory aggregator

- .pre-commit-config.yaml
> add pre-commit-config.yaml

- .github/workflows/tests.yaml
- environment.yml
Related to https://github.com/anitagraser/movingpandas/issues/143#issuecomment-996046908
Again taken from https://github.com/geopandas/geopandas/blob/master/.github/workflows/tests.yaml
> add testing in GHA

- .github/workflows/tests.yaml
- codecov.yml
Tests working now. I will add linting in later.
Note: you may need to have codecov secrets setup in the repo for the GHA to push to codecov. May want to switch off the Travis CI pipeline if you are happy with this to check everything works. You may want to update the badges in the README as well.
I also copied the codecov.yml from geopandas.
> comment out needs: Linting

- movingpandas/trajectory_aggregator.py
Hand edit to trajectory_aggregator.py to comply with black and flake8
> black and flake8 trajectory_aggregator.py

- movingpandas/__init__.py
- movingpandas/tests/test_trajectory_cleaner.py
- movingpandas/trajectory_cleaner.py
Added new cleaner base class as well as an outlier (iqr) based cleaning method + accompanying tests.
Checked flake8 btw
Issue #129
> Cleaner base class and functionality + tests

- environment.yml
- setup.py
> Remove pin to early (pre 1.8) versions of shapely

- movingpandas/tools/_show_versions.py
Somewhat related to https://github.com/anitagraser/movingpandas/issues/178
This will show if stonesoup is installed, otherwise will return None
> add stonesoup in show_versions

- movingpandas/trajectory_generalizer.py
Reference taken from https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm
> DOC: Douglas and Pecker reference

- movingpandas/trajectory_smoother.py
Closes https://github.com/anitagraser/movingpandas/issues/192
> DOC: KalmanSmootherCV.smooth parameter info

- movingpandas/tests/test_trajectory.py
- movingpandas/trajectory.py
Follow on from https://github.com/anitagraser/movingpandas/pull/151
Add name arg to `add_direction` and `add distance`.
> add name arg to direction and distance

- movingpandas/trajectory.py
some refactoring while looking at https://github.com/anitagraser/movingpandas/issues/245
> _get_df_with_timedelta refactor

- movingpandas/io.py
- movingpandas/overlay.py
- movingpandas/point_clusterer.py
- movingpandas/tests/test_trajectory.py
- movingpandas/tools/_show_versions.py
- movingpandas/trajectory.py
- movingpandas/trajectory_aggregator.py
- movingpandas/trajectory_collection.py
- movingpandas/trajectory_generalizer.py
- movingpandas/trajectory_splitter.py
- movingpandas/trajectory_stop_detector.py
1. Use f-strings
2. Use integers where appropriate
3. Simplify loops
4. Use statistics module
5. Refactor repetitive code
> Modernize code

- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory.py
- movingpandas/trajectory_collection.py
Better formatting of docstrings and added missing TrajectoryCollection convenience functions for adding columns
> Improved docstrings, fixes #355

- movingpandas/overlay.py
- movingpandas/tests/test_trajectory_aggregator.py
- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory.py
- movingpandas/trajectory_generalizer.py
- movingpandas/trajectory_splitter.py
- movingpandas/trajectory_stop_detector.py
- movingpandas/unit_utils.py
1. Use `math.hypot`
2. Simplify DataFrame manipulation
3. Simplify loops
> Simplify code

- movingpandas/tests/test_trajectory_collection.py
- movingpandas/tools/_multi_threading.py
- movingpandas/trajectory_collection.py
- movingpandas/trajectory_plotter.py
- movingpandas/trajectory_stop_detector.py
- tutorials/7-multithreading.ipynb
> Make TrajectoryCollection operations multi-threaded

- docs/environment.yml
- docs/source/conf.py
- environment-minimum.yml
- setup.py
See https://github.com/movingpandas/movingpandas/issues/417
> Remove fiona

- movingpandas/tests/test_trajectory.py
- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory.py
- movingpandas/trajectory_collection.py
- movingpandas/trajectory_plotter.py
- tutorials/0-debug.ipynb
- tutorials/1-getting-started.ipynb
- tutorials/2-reading-data-from-files.ipynb
- tutorials/3-generalization-and-aggregation.ipynb
- tutorials/4-stop-detection.ipynb
- tutorials/5-local-coordinates.ipynb
- tutorials/6-trajectory-metrics.ipynb
- tutorials/7-multithreading.ipynb
- tutorials/8-ogc-moving-features.ipynb
Refers to issue: https://github.com/movingpandas/movingpandas/issues/418
> Update explore() function to plot speed

- movingpandas/trajectory_plotter.py
This should solve #344 and so the 'grey' values can be removed [from this notebook](https://github.com/movingpandas/movingpandas-examples/blob/main/2-analysis-examples/ship-data.ipynb).
> Plot lines grey for categories missing from colormap

- movingpandas/overlay.py
- movingpandas/tests/test_trajectory_collection.py
- movingpandas/trajectory_plotter.py
Fixes https://github.com/movingpandas/movingpandas/issues/236#issuecomment-2541259052
> Fix traj clipping with complex geometries

- movingpandas/tests/test_trajectory_splitter.py
- movingpandas/trajectory_splitter.py
>  Prevent gaps in splitter results, fixes #446 

- movingpandas/geometry_utils.py
- movingpandas/tests/test_geometry_utils.py
- movingpandas/tests/test_trajectory_splitter.py
- movingpandas/trajectory_splitter.py
> Ensure CRS of split is correct

- movingpandas/trajectory.py
> Remove redundant decorators (#473)
